#!/usr/bin/env python
from __future__ import print_function

import cubefit

from argparse import ArgumentParser

parser = ArgumentParser(description="DDT: Datacube Deconvolution Thingy")
parser.add_argument("filename", help="configuration file")
parser.add_argument("data_dir", help="directory containing FITS data files")
parser.add_argument("output_filename", help="Output filename")
args = parser.parse_args()

cubefit.main(args.filename, args.data_dir, args.output_filename)
