#!/usr/bin/env python
from __future__ import print_function

import ddtpy

def main():
    from argparse import ArgumentParser

    parser = ArgumentParser(
        description="DDT: Datacube Deconvolution Thingy")
    parser.add_argument("filename", help="path to configuration file")

    args = parser.parse_args()

    ddt = ddtpy.DDT(args.filename)
    print(ddt)

main()
