#!/usr/bin/env python
from __future__ import print_function

import cPickle as pickle
from argparse import ArgumentParser
import ddtpy

parser = ArgumentParser(description="ddt-plot")
parser.add_argument("result_filename",
                    help="output from ddt-fit (.pkl file)")
parser.add_argument("figure_filename", help="target filename")
args = parser.parse_args()

f = open(args.result_filename, 'rb')
result_dict = pickle.load(f)
f.close()

ddtpy.plot_timeseries(result_dict, fname=args.figure_filename)
