#!/usr/bin/env python
from __future__ import print_function

import ddtpy

from argparse import ArgumentParser

parser = ArgumentParser(description="DDT: Datacube Deconvolution Thingy")
parser.add_argument("filename", help="configuration file")
parser.add_argument("data_dir", help="directory containing FITS data files")

args = parser.parse_args()

ddtpy.main(args.filename, args.data_dir)
