#!/usr/bin/env python
from __future__ import print_function

import cPickle as pickle
from argparse import ArgumentParser
import ddtpy

parser = ArgumentParser(description="ddt-plot")
parser.add_argument("result_filename",
                    help="output from ddt-fit (.pkl file)")
parser.add_argument("figure_prefix", help="output prefix")
parser.add_argument("parameter_file", help="ddt input json file")
parser.add_argument('-b', '--band', help='timeseries band', default='B',
                    dest='band')

args = parser.parse_args()

f = open(args.result_filename, 'rb')
result_dict = pickle.load(f)
f.close()

ddtpy.plot_timeseries(result_dict, fname='%s_timeseries.eps' 
                      % args.figure_prefix, band=args.band)
ddtpy.plot_wave_slices(result_dict, fname='%s_waveslice.eps' 
                       % args.figure_prefix)
ddtpy.plot_sn(result_dict, args.parameter_file,
	      fname='%s_sn.eps' % args.figure_prefix)

